/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}


import {
  Toasty as WopToasty
} from './components/wop-toasty/wop-toasty';

declare global {
  interface HTMLWopToastyElement extends WopToasty, HTMLStencilElement {
  }
  var HTMLWopToastyElement: {
    prototype: HTMLWopToastyElement;
    new (): HTMLWopToastyElement;
  };
  interface HTMLElementTagNameMap {
    "wop-toasty": HTMLWopToastyElement;
  }
  interface ElementTagNameMap {
    "wop-toasty": HTMLWopToastyElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "wop-toasty": JSXElements.WopToastyAttributes;
    }
  }
  namespace JSXElements {
    export interface WopToastyAttributes extends HTMLAttributes {
      img?: string;
      sound?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
